services:
  - type: web
    name: 3d-print-calculator-backend
    env: python
    plan: free
    buildCommand: |
      python generate_requirements.py
      pip install -r requirements.txt
    startCommand: |
      python -c "
      from backend.database import wait_for_db, init_db
      wait_for_db(max_retries=20, retry_delay=10)
      init_db()
      "
      uvicorn backend.api:app --host 0.0.0.0 --port ${PORT}
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 3d-print-calculator-db
          property: connectionString

  - type: web
    name: 3d-print-calculator-frontend
    env: python
    plan: free
    buildCommand: |
      python generate_requirements.py
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port ${PORT}
    envVars:
      - key: BACKEND_URL
        value: https://3d-print-calculator-backend.onrender.com

databases:
  - name: 3d-print-calculator-db
    plan: free
    ipAllowList: []